#!/usr/bin/env python3
"""Compile the stages listed in shaders/variants.json to SPIR-V and emit the registry table.

Each manifest entry names one stage source under shaders/, its glslang stage, and the
defines it is compiled with. SPIR-V goes to shaders/spv/<name>.spv on every run and is not
committed; src/c3d/shader/variants.c3, with the ShaderName enum, flag constants, and the
embedded table, is committed.

  scripts/build_shaders.py            compile every entry and write the registry table
  scripts/build_shaders.py --check    compile every entry; fail if the committed table is out of date
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHADERS = ROOT / "shaders"
MANIFEST = SHADERS / "variants.json"
SPIRV = SHADERS / "spv"
GENERATED_C3 = ROOT / "src" / "c3d" / "shader" / "variants.c3"
INCLUDE_DIRS = (
    SHADERS / "generated",
    SHADERS / "common",
    ROOT / "lib" / "gpu.c3l" / "include" / "shaders",
)

TARGET_ENV = "vulkan1.3"
# Keep discard available without requesting shaderDemoteToHelperInvocation.
TARGET_SPIRV = "spirv1.5"
INCLUDE_PREAMBLE = "#extension GL_GOOGLE_include_directive : enable"
EMBED_PREFIX = "../../../shaders/spv/"
STAGES = (
    "vert", "frag", "comp", "geom", "tesc", "tese",
    "rgen", "rmiss", "rchit", "rahit", "rint", "rcall",
    "task", "mesh",
)
MAX_FLAGS = 24
MAX_SHADERS = 256

EXIT_FAILED = 1


class ManifestError(Exception):
    pass


@dataclass(frozen=True)
class Entry:
    shader: str
    source: Path
    stage: str
    defines: tuple[str, ...]

    @property
    def spirv_name(self) -> str:
        suffix = "".join(f"_{define.lower()}" for define in self.defines)
        return f"{self.shader}{suffix}.spv"

    @property
    def embed_constant(self) -> str:
        return f"{Path(self.spirv_name).stem.upper()}_SPIRV"


def log(message: str) -> None:
    print(f"[shaders] {message}", flush=True)


def load_manifest() -> tuple[list[str], list[Entry]]:
    with MANIFEST.open() as handle:
        manifest = json.load(handle)
    flags: list[str] = list(manifest.get("flags", []))
    if len(flags) > MAX_FLAGS:
        raise ManifestError(f"{len(flags)} flags declared; ShaderVariant holds {MAX_FLAGS}")
    if len(set(flags)) != len(flags):
        raise ManifestError("duplicate flag names")

    entries: list[Entry] = []
    seen: set[tuple[str, tuple[str, ...]]] = set()
    for raw in manifest.get("entries", []):
        shader = raw["shader"]
        stage = raw["stage"]
        if stage not in STAGES:
            raise ManifestError(f"{shader}: unknown stage '{stage}'")
        source = SHADERS / raw["source"]
        if not source.exists():
            raise ManifestError(f"{shader}: source {source.relative_to(ROOT)} does not exist")
        unknown = [define for define in raw.get("defines", []) if define not in flags]
        if unknown:
            raise ManifestError(f"{shader}: defines not declared in flags: {', '.join(unknown)}")
        defines = tuple(flag for flag in flags if flag in raw.get("defines", []))
        key = (shader, defines)
        if key in seen:
            raise ManifestError(f"{shader}: duplicate entry for defines {list(defines)}")
        seen.add(key)
        entries.append(Entry(shader, source, stage, defines))

    shaders = shader_names(entries)
    if len(shaders) > MAX_SHADERS:
        raise ManifestError(f"{len(shaders)} shader names; ShaderVariant holds {MAX_SHADERS}")
    return flags, entries


def shader_names(entries: list[Entry]) -> list[str]:
    names: list[str] = []
    for entry in entries:
        if entry.shader not in names:
            names.append(entry.shader)
    return names


def compile_one(glslang: str, entry: Entry, output: Path, verbose: bool) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    command = [
        glslang,
        "-V",
        "--target-env", TARGET_ENV,
        "--target-env", TARGET_SPIRV,
        "-S", entry.stage,
        f"-P{INCLUDE_PREAMBLE}",
    ]
    command += [f"-D{define}" for define in entry.defines]
    command += [f"-I{directory}" for directory in INCLUDE_DIRS]
    command += ["-o", str(output), str(entry.source)]
    if verbose:
        log(f"$ {' '.join(command)}")
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL)


def emit_variants_c3(flags: list[str], entries: list[Entry]) -> str:
    lines = [
        f"// Generated by build_shaders.py from {MANIFEST.relative_to(ROOT)} - do not edit.",
        "module c3d::shader;",
        "",
        "<*",
        " Stage families compiled into the registry.",
        "*>",
        "enum ShaderName : int {",
    ]
    lines += [f"    {name.upper()}," for name in shader_names(entries)]
    lines.append("}")

    for bit, flag in enumerate(flags):
        lines += [
            "",
            "<*",
            f" Flag bit for {flag}.",
            "*>",
            f"const uint SHADER_FLAG_{flag} = 1 << {bit};",
        ]

    lines.append("")
    for entry in entries:
        lines.append(
            f'const char[*] {entry.embed_constant} @private = $embed("{EMBED_PREFIX}{entry.spirv_name}");'
        )

    lines += [
        "",
        "<*",
        " Every compiled stage, in manifest order.",
        "*>",
        f"const ShaderEntry[{len(entries)}] SHADER_ENTRIES = {{",
    ]
    for entry in entries:
        variant = f".shader = {entry.shader.upper()}"
        if entry.defines:
            mask = " | ".join(f"SHADER_FLAG_{define}" for define in entry.defines)
            variant += f", .flags = {mask}"
        lines.append(f"    {{ .variant = {{ {variant} }}, .spirv = {entry.embed_constant}[..] }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def compile_all(glslang: str, entries: list[Entry], verbose: bool) -> None:
    for entry in entries:
        compile_one(glslang, entry, SPIRV / entry.spirv_name, verbose)


def table_is_current(flags: list[str], entries: list[Entry]) -> bool:
    expected = emit_variants_c3(flags, entries)
    return GENERATED_C3.exists() and GENERATED_C3.read_text(encoding="utf-8") == expected


def write_table(flags: list[str], entries: list[Entry]) -> None:
    GENERATED_C3.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_C3.write_text(emit_variants_c3(flags, entries), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="c3d shader compilation")
    parser.add_argument("--glslang", default="glslangValidator", help="glslang executable")
    parser.add_argument("--check", action="store_true", help="verify the committed registry table instead of writing it")
    parser.add_argument("--verbose", action="store_true", help="print every command")
    arguments = parser.parse_args()

    if not MANIFEST.exists():
        log(f"no manifest at {MANIFEST.relative_to(ROOT)}")
        return 0

    glslang = shutil.which(arguments.glslang)
    if glslang is None:
        log(f"'{arguments.glslang}' not found on PATH")
        return EXIT_FAILED

    try:
        flags, entries = load_manifest()
        compile_all(glslang, entries, arguments.verbose)
        if arguments.check:
            if not table_is_current(flags, entries):
                log(f"stale: {GENERATED_C3.relative_to(ROOT)} (run scripts/build.py --regen)")
                return EXIT_FAILED
        else:
            write_table(flags, entries)
    except ManifestError as error:
        log(f"manifest error: {error}")
        return EXIT_FAILED
    except subprocess.CalledProcessError as error:
        log(f"glslang failed ({error.returncode})")
        return EXIT_FAILED

    log(f"compiled {len(entries)} stage(s), table {'checked' if arguments.check else 'written'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
